### ISSUE TITLE
Unable to load shared library 'python37'  on linux

### ISSUE THREAD

**Issue by IvanAntipov** [henon/pythonnet_netstandard#16]
### Environment

-   Pythonnet version:
```
<PackageReference Include="pythonnet_netstandard_py37_linux" Version="2.5.1.1" />
``` 

-   Python version:
```
Python 3.7.7 (default, Apr 30 2020, 00:18:01)
[GCC 7.4.0] on linux
```
-   Operating System:
```
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"

```
-  dotnet
```
.NET SDK (5.0.101)
```

### Details

-   Describe what you were trying to get done.
main.fsx
```fsharp

#I @"bin"
#r @"Python.Runtime.dll" 
open Python.Runtime
use gil = Py.GIL()


```

-   If there was a crash, please include the traceback here.
```

System.DllNotFoundException: Unable to load shared library 'python37' or one of its dependencies. In order to help diagnose loading problems, consider setting t
he LD_DEBUG environment variable: libpython37: cannot open shared object file: No such file or directory
   at Python.Runtime.Runtime.Py_IsInitialized()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize()
   at Python.Runtime.Py.GIL()
   at <StartupCode$FSI_0002>.$FSI_0002.main@()
```

### Additional

``` /usr/local/bin``` doesn't conatains `python37`

There are `python3`, `python3.7`, `python3.7`

**Comment by IvanAntipov** [comment]
I have further investigated the problem, apparently it is my local problem on build side.

Perhaps, one of the dependent projects accidentally hooked the old Python. Runtime version. I apologize for the wrong issue.
